baseURL = 'https://mohamed-hamoud.com/'
languageCode = 'en-us'
title = 'Mohamed Hamoud'
theme = 'gokarna-hugo'
canonifyURLs = true


[params]
socialIcons = [
    {name = "email", url = "mailto:mohamed.hamoud@df.uzh.ch"},
    {name = "linkedin", url = "https://www.linkedin.com/in/mohamdhamoud/"},
    {name = "googlescholar", url = "https://scholar.google.com/citations?user=aQ0yYCUAAAAJ&hl=en"},
    {name = "ssrn", url = "https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=7008318"},
]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Research"
url = "/research/"
weight = 2

[[menu.main]]
name = "Teaching"
url = "/teaching/"
weight = 3

[[menu.main]]
name = "CV"
url = "/cv/CV.pdf"
weight = 4
